### ISSUE TITLE
Unable to create plugin

### ISSUE THREAD

**Issue by jtliang24** [H3rmt/hyprswitch#321]
I get a popup saying: Unable to load hyprland plugin.

Otherwise, functionality seems unaffected.

This is started using the system service, on NixOS, Hyprland v0.49.0

Here are the journalctl logs

```
Sep 05 10:24:27 nixos hyprshell[2622]:    0.372401959s TRACE activate:create_binds:load_plugin: plugins: [Plugin { name: "Hyprspace", author: "KZdkm", handle: "af3ff20", version: "0.1", description: "Workspace >
Sep 05 10:24:27 nixos hyprshell[2622]:    0.372733995s TRACE activate:create_binds:load_plugin:generate: extracting plugin from zip
Sep 05 10:24:27 nixos hyprshell[2622]:    0.373499272s TRACE activate:create_binds:load_plugin:generate: extracted 5 files
Sep 05 10:24:27 nixos hyprshell[2622]:    0.373508418s TRACE activate:create_binds:load_plugin:generate: configuring defs file
Sep 05 10:24:27 nixos hyprshell[2622]:    0.373602340s TRACE activate:create_binds:load_plugin:generate: building plugin
Sep 05 10:24:27 nixos hyprshell[2622]:    0.373611256s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpuaFITnhyprshell-hyprland-plugin"}: PATH: Some("/run/wrappers/bin:/home/jtliang/.local>
Sep 05 10:24:27 nixos hyprshell[2622]:    0.373623217s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpuaFITnhyprshell-hyprland-plugin"}: CPATH: None
Sep 05 10:24:27 nixos hyprshell[2622]:    0.373629768s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpuaFITnhyprshell-hyprland-plugin"}: Running build command: cd "/tmp/.tmpuaFITnhyprshel>
Sep 05 10:24:27 nixos hyprshell[2622]:    0.374191792s  WARN activate:create_binds: Failed to load hyprland plugin: Failed to load hyprland plugin
Sep 05 10:24:27 nixos hyprshell[2622]: Caused by:
Sep 05 10:24:27 nixos hyprshell[2622]:     0: unable to generate plugin
Sep 05 10:24:27 nixos hyprshell[2622]:     1: Failed to build plugin
Sep 05 10:24:27 nixos hyprshell[2622]:     2: Failed to spawn build process
Sep 05 10:24:27 nixos hyprshell[2622]:     3: No such file or directory (os error 2)
Sep 05 10:24:27 nixos hyprshell[2622]:    0.374214462s  INFO activate:create_binds: Falling back to default keybinds
Sep 05 10:24:27 nixos hyprshell[2622]:    0.374232573s TRACE activate:create_binds: binding exec: Binding { mods: [SUPER], key: Key("tab"), flags: [], dispatcher: Exec("/nix/store/5xprfpbzvmj8sgkj6hq8pjr05mz7ki>
Sep 05 10:24:27 nixos hyprshell[2622]:    0.375181188s TRACE activate:create_binds: layerrules applied
```

**Comment by H3rmt** [comment]
I am facing some issues regarding the nix packaging

**Comment by H3rmt** [comment]
https://github.com/H3rmt/hyprshell/blob/hyprshell-release/nix%2Fbuild.nix#L19

This hook is never run, idk why, it functioned in the past. I did some testing and now the hook runs, but fails to successfully wrap the program. (The hook also still runs after being deleted which is very confusing)

**Comment by H3rmt** [comment]
If anyone has any clue on how to solve this I will gladly take any advice

**Comment by H3rmt** [comment]
Just fixed it

**Comment by H3rmt** [comment]
So it is fixed in 4.6.3, but it doesnt work if you use the hyprland flake.

Hyprshell builds the plugin at buildtime so it needs the hyprland headers in its CPATH which is being done with wrapProgram in `./nix/build.nix`. 
If you use 
```nix
wayland.windowManager.hyprland = {
  enable = true;
  # set the flake package
  package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
  portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland;
};
```
this the headers dont match.

**Comment by chungyinleo** [comment]
I tried 3 different things, all using the hyprshell flake, configured with home-manager:

1. Without using hyprland flake

Plugin is loaded, hyprshell is started without warnings. However, alt tabbing still closes immediately when focused window is receiving text input. Additionally, the launcher and overview also close immediately on the same condition, which does not happen on the previous version without the plugin loaded

2. Using the hyprland flake pinned at v50.1

Same as 1 because that is what nixpkgs uses.

3.  Using the hyprland flake at main branch

Plugin cannot be loaded because of header mismatch, but everything else works, including alt tabbing.

I am only a user that really loves hyprshell, but not familiar with rust nor nix packaging. Hope this helps.

**Comment by H3rmt** [comment]
I noticed that the follow mouse command fails in hyprland 50.1, I need to check why (this should force the cursor to switch to the launcher and not allow the window underneath to capture key presses

**Comment by jtliang24** [comment]
I am still getting a popup on Hyprland 0.49, even using hyprshell 4.6.3, but it is now a header mismatch.

```
Sep 11 11:27:58 nixos hyprshell[2652]:    0.528270805s TRACE activate:load_config{path="/home/jtliang/.config/hyprshell/config.json"}: No migration needed
Sep 11 11:27:58 nixos hyprshell[2652]:    0.528571448s DEBUG activate:load_config{path="/home/jtliang/.config/hyprshell/config.json"}: Loaded config
Sep 11 11:27:58 nixos hyprshell[2652]:    0.528885116s TRACE activate:create_binds:load_plugin: plugins: [Plugin { name: "Hyprspace", author: "KZdkm", handle: "206155b0", version: "0.1", description: "Workspace overview" }]
Sep 11 11:27:58 nixos hyprshell[2652]:    0.528926805s TRACE activate:create_binds:load_plugin:generate: extracting plugin from zip
Sep 11 11:27:58 nixos hyprshell[2652]:    0.529110569s TRACE activate:create_binds:load_plugin:generate: extracted 5 files
Sep 11 11:27:58 nixos hyprshell[2652]:    0.529120548s TRACE activate:create_binds:load_plugin:generate: configuring defs file
Sep 11 11:27:58 nixos hyprshell[2652]:    0.529184007s TRACE activate:create_binds:load_plugin:generate: building plugin
Sep 11 11:27:58 nixos hyprshell[2652]:    0.529194226s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpmT860Ahyprshell-hyprland-plugin"}: PATH: Some("/nix/store/95k9rsn1zsw1yvir8mj824ldhf90i4qw-gcc-wrapper-14.3.0/bin:/run/wrappers/bin:/home/jtliang/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/home/jtliang/.nix-profile/bin:/nix/profile/bin:/home/jtliang/.local/state/nix/profile/bin:/etc/profiles/per-user/jtliang/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/nix/store/87zpmcmwvn48z4lbrfba74b312h22s6c-binutils-wrapper-2.44/bin:/nix/store/5xsczfy0i6b4cld4064iwp4gvq51gj61-hyprland-qtutils-0.1.4/bin:/nix/store/cz994zlb77rlfqhp8vps5hzv6v4830rx-pciutils-3.13.0/bin:/nix/store/m53q460bmkxmnwk52jknjsw49kgc1y81-pkgconf-wrapper-2.4.3/bin")
Sep 11 11:27:58 nixos hyprshell[2652]:    0.529207100s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpmT860Ahyprshell-hyprland-plugin"}: CPATH: Some("/nix/store/w4djr9imy5rszqhigdmxbif34pg6mwi5-aquamarine-0.9.4-dev/include:/nix/store/d7i09anhjnmavn42210ai7ash9dyrcqf-cairo-1.18.4-dev/include:/nix/store/ynvchd9v9wip8y21yjw7amklywy5v2b5-glaze-5.5.5/include:/nix/store/q1zaii9cirbfpmwr7d86hpppql3kjcpf-git-2.51.0/include:/nix/store/y5z7vm4jiff680kz5ry8xwqqsk7z7wh8-hyprcursor-0.1.13-dev/include:/nix/store/j86dapbh8s7x0wnng2bni4ak92f03jbv-hyprgraphics-0.1.5-dev/include:/nix/store/nn39zmgzydxyffjw1iqih9yqgvhvqg7w-hyprlang-0.6.4-dev/include:/nix/store/g4fyndxskxpfhwvi1qifcks1bjk7ssi2-hyprutils-0.8.4-dev/include:/nix/store/7arx12axvy20ls0swyhvm4mia2bq5b8c-libglvnd-1.7.0-dev/include:/nix/store/myrhngjdaz6fxk4izl3phi0l0p7zir61-libdrm-2.4.125-dev/include:/nix/store/sjrgmkq1ad15z3w6g0am0avk3mwhwb2j-libinput-1.29.0-dev/include:/nix/store/drjdazfxbhm4ywgzrrq08nrfpylkpahl-util-linux-minimal-2.41.1-dev/include:/nix/store/y300dk1dnb8rkl9vnm4zv0ih6jffidyb-libxkbcommon-1.11.0-dev/include:/nix/store/20qx2p8y7dq21bh35wkad8n05qmar118-mesa-libgbm-25.1.0/include:/nix/store/c2nmrh02fwlk1hklc36swf5b87ag2573-pango-1.56.3-dev/include:/nix/store/z1da5dc3ci6qg62a50g11aw7vz2xawaa-pciutils-3.14.0/include:/nix/store/c95kq2lazqx6yw5an9hilvfg2kn2h0pl-re2-2025-08-12-dev/include:/nix/store/7alnq2nw4mn3wm13j3vrh99xi4kazlsk-tomlplusplus-3.4.0/include:/nix/store/799yc9m4iflqpnaw831zc586zwc5k36a-wayland-1.24.0-dev/include:/nix/store/gm122hm4w9qvmwfk45mxm4kbblcr308y-wayland-protocols-1.45/include:/nix/store/r9gz70aynd100n4plmx51ysvy285chbx-libxcursor-1.2.3-dev/include:/nix/store/chz1jkz2lk7vpalrm8qvra2616yr8jh0-libxcb-1.17.0-dev/include:/nix/store/25vj6bic32igb55m80d4h7ic0d0k7553-libxdmcp-1.1.5-dev/include:/nix/store/sdkx8hzlpbmypk2pmnb9j3znhmwnyhsz-libxcb-errors-1.0.1-dev/include:/nix/store/cdcvcj9i845b5zxfp2fcffxq6420l5m4-libxcb-wm-0.4.2-dev/include:/nix/store/kg2gwgq3l932r1q6dl3sgn3kfpad30gd-xwayland-24.1.8/include:/nix/store/chxx1z0rwh85pll0jpyq0xblr6xs48p3-systemd-257.8-dev/include:/nix/store/wl8cgn8mhhi6mkp5yryj90dcvk4fyy14-hyprland-0.50.1-dev/include:/nix/store/ssshfj3zgwnx3j77spypa7c5v5ixc5sc-pixman-0.46.2/include")
Sep 11 11:27:58 nixos hyprshell[2652]:    0.529236906s TRACE activate:create_binds:load_plugin:generate:build{path="/tmp/.tmpmT860Ahyprshell-hyprland-plugin"}: Running build command: cd "/tmp/.tmpmT860Ahyprshell-hyprland-plugin" && "gcc" "-shared" "-fPIC" "--no-gnu-unique" "-std=c++2b" "-I/usr/include/pixman-1" "-O2" "-o" "/tmp/hyprshell.so" "all.cpp"
Sep 11 11:27:58 nixos hyprshell[2652]:    0.529598944s DEBUG preactivate:reload_icons: found 1111 icons from filesystem in "/run/current-system/sw/share/icons" paths (in background)
Sep 11 11:28:01 nixos hyprshell[2652]:    2.941854004s TRACE activate:create_binds:load_plugin: generated plugin at "/tmp/hyprshell.so"
Sep 11 11:28:01 nixos hyprshell[2652]:    2.978873233s  WARN activate:create_binds: Failed to load hyprland plugin: Failed to load hyprland plugin
Sep 11 11:28:01 nixos hyprshell[2652]: Caused by:
Sep 11 11:28:01 nixos hyprshell[2652]:     0: unable to load plugin
Sep 11 11:28:01 nixos hyprshell[2652]:     1: Plugin /tmp/hyprshell.so could not be loaded: plugin crashed/threw in main: [Hyprshell Plugin] Version mismatch
Sep 11 11:28:01 nixos hyprshell[2652]:    2.978913268s  INFO activate:create_binds: Falling back to default keybinds
Sep 11 11:28:01 nixos hyprshell[2652]:    2.978947382s TRACE activate:create_binds: binding exec: Binding { mods: [SUPER], key: Key("tab"), flags: [], dispatcher: Exec("/nix/store/4rc7m7mgjx2d5dm0g491fm7wpzmkjljd-hyprshell-4.6.3/bin/..hyprshell-wrapped-wrapped socat '\"OpenOverview\"'") }
Sep 11 11:28:01 nixos hyprshell[2652]:    3.031967093s TRACE activate:create_binds: layerrules applied
```

**Comment by H3rmt** [comment]
The nix version currently uses the hyprland nix-unstable headers, should be 0.50

**Comment by jtliang24** [comment]
Okay, I have updated to the Hyprland package in the nixpkgs-unstable and that has fixed the issue.

**Comment by H3rmt** [comment]
Remaining issues regarding plugins are tracked in separate issue

**Comment by H3rmt** [comment]
I added a option to set the used hyprland package. this automaticaly wraps hyprshell with the correct version of hyprland headers. released in `v4.6.4`

**Comment by chungyinleo** [comment]
This works well, but I have a suggestion that may make the experience more consistent with other flakes.

Is it possible to add a hyprland flake pinned at a stable version as an input, and build the plugin using the package from hyprland flake instead of nixpkgs?

If users use different revision of the hyprland flake, they can just add `hyprshell.inputs.hyprland.follows = "hyprland"` in `flake.nix`

This is also done in the official [hyprland-plugins repo](https://github.com/hyprwm/hyprland-plugins)

**Comment by H3rmt** [comment]
This would most likely make caching with cachix unusable, I think?

It is acceptable for the plugins as most are build in a couple of seconds, but hyprshell takes some time to build when using the flake. This method is a bit unconventional, but allows for hyprshell to be cached with cachix but also run with any custom version of hyprland. 
The dependencies also are only required a runtime and not at buildtime which allows the full binary to be cached

**Comment by jennydaman** [comment]
https://github.com/NixOS/nixpkgs/pull/443211 just landed in nixpkgs-unstable, however the OP error is still happening. On my system, I have Hyprland and hyprshell installed from nixpkgs using home-manager.

- `/nix/store/8vp44639k9gl2p7f19mfd1mma4s5xssw-hyprshell-4.6.4/bin/hyprshell`
- `/nix/store/am1i012zxjsm6k43j14jnc19jinsyybp-hyprland-0.51.0/bin/Hyprland`

https://github.com/H3rmt/hyprshell/blob/5545fdaf81bbfdd616ddc9b5ec05db494dd9e693/NIX.md?plain=1#L43

It does not seem true that the hyprland C headers from nixpkgs-unstable are available.

**Comment by H3rmt** [comment]
https://github.com/NixOS/nixpkgs/pull/445042

Is pending

**Comment by jennydaman** [comment]
Ah, I didn't realize the fix was a part of a separate PR.

The least I could do is help you test, I set `nixpkgs.url = "github:nixos/nixpkgs?ref=pull/445042/head";` and confirmed everything works.
